#!/bin/bash

URL=http://93.123.36.180:1935/cdn/ngrp:fln_eng.stream_all
PLAYLIST_URL=$URL/chunklist_b1728000.m3u8
PLAYLIST_NAME=bnt1_480p
PLAYLIST_PATH=/tmp/wwwroot
PLAYLIST_SUFFIX=m3u8
PLAYLIST=$PLAYLIST_PATH/$PLAYLIST_NAME.$PLAYLIST_SUFFIX
INSERT_SCILLA_PHP=/root/cassandra/write_chunks_in_scylla.php
PHP_BIN=/usr/bin/php
NEW=new.md5
LAST=last.md5

touch $PLAYLIST_PATH/$LAST

while true; do

  curl -s -sH 'Accept-encoding: gzip' --compressed $PLAYLIST_URL|tail -n2>$PLAYLIST
  md5sum $PLAYLIST>$PLAYLIST_PATH/$NEW
  diff $PLAYLIST_PATH/$NEW $PLAYLIST_PATH/$LAST

  if [ $? -eq 1 ]; then
    cp $PLAYLIST_PATH/$NEW $PLAYLIST_PATH/$LAST
    LAST_MEDIA=$(tail -n 2 $PLAYLIST|tr -d "\n")
    LAST_MEDIA_INFO=(${LAST_MEDIA//,/ })
    CHUNK_DURATION=${LAST_MEDIA_INFO[0]#*:}
    CHUNK_FILENAME=${LAST_MEDIA_INFO[1]}
    wget -O $PLAYLIST_PATH/$CHUNK_FILENAME $URL/$CHUNK_FILENAME
    $PHP_BIN $INSERT_SCILLA_PHP $PLAYLIST_NAME $PLAYLIST_PATH $CHUNK_FILENAME $CHUNK_DURATION
    rm $PLAYLIST_PATH/$CHUNK_FILENAME
  fi
  sleep 1
done
